test_subnet_create_delete (myrally.test.concurrent_test.ConcurrentSubnetTest) ... ERROR

======================================================================
ERROR: test_subnet_create_delete (myrally.test.concurrent_test.ConcurrentSubnetTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/vagrant/package/myrally/test/concurrent_test.py", line 95, in setUp
    self.vpc_id = resp['CreateVpcResponse']['vpc']['vpcId']
KeyError: 'CreateVpcResponse'

----------------------------------------------------------------------
Ran 1 test in 3.990s

FAILED (errors=1)
